name: waveplayer
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11
  on_audio_query: ^2.9.0
  path_provider: ^2.1.2
  provider: ^6.1.1
  youtube_explode_dart: ^2.2.2
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/default_cover.png
